#!/bin/sh
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#   Description:
#       This script notifies about NCP state changes.
#

PID=$$
NAME="ncp_state_notifier"

DISPATCHER_PATH="/etc/ncp_state_notifier/dispatcher.d"

echo ${PID} > "/tmp/${NAME}.pid"

if [ -z ${IFACE} ]; then
    IFACE="wpan0"
fi

WPANTUND_IFACE="com.nestlabs.WPANTunnelDriver"
WPANTUND_NCP_STATE_PATH="/com/nestlabs/WPANTunnelDriver/${IFACE}/Properties/NCP/State"

WATCH1="type='signal', interface=${WPANTUND_IFACE}, path=${WPANTUND_NCP_STATE_PATH}, member='PropertyChanged'"

notify_about_state()
{
    logger -t "${NAME}[${PID}]" "Notifying about change state to: ${1} on the interface: ${2}"

    for SCRIPT in `find ${DISPATCHER_PATH} -type f`; do
        logger -t "${NAME}[${PID}]" "Running script: ${SCRIPT}"
        .${SCRIPT} ${1} ${2}
    done
}

process_output()
{
    local NEXT_LINE_IS_STATE=0

    while read -r LINE; do
        if echo ${LINE} | grep -q "NCP:State"; then
            NEXT_LINE_IS_STATE=1
            continue
        fi

        if [ ${NEXT_LINE_IS_STATE} -eq 1 ]; then
            NEXT_LINE_IS_STATE=1

            STATE=`echo ${LINE} | cut -d'"' -f2`
            notify_about_state ${STATE} ${IFACE}
        fi
    done
}

dbus-monitor --system "${WATCH1}" | process_output
