#!/bin/sh
#
# Start KNoTd
#

start() {
        printf "Starting KNoTd: "
        if /etc/knot/start.sh knotd
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

stop() {
        printf "Stopping KNoTd: "
        if /etc/knot/stop.sh knotd
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

restart() {
        stop
        start
}


case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
