#!/bin/sh
#
# Starts brcmfmac.
#

start() {
	printf "Starting brcmfmac: "
	modprobe brcmfmac
	echo "OK"
}
stop() {
	printf "Stopping brcmfmac: "
	rmmod brcmfmac
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

