#!/bin/sh
#
# Starts cdc_acm.
#

start() {
	printf "Starting tun: "
	modprobe cdc_acm
	echo "OK"
}
stop() {
	printf "Stopping tun: "
	rmmod cdc_acm
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

