#!/bin/sh
#
# spi        Starts spi-bcm2835.
#

start() {
	printf "Starting spi-bcm2835: "
	modprobe spi-bcm2835
	echo "OK"
}
stop() {
	printf "Stopping spi-bcm2835: "
	rmmod spi-bcm2835
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

