#!/bin/sh
#
# Start nrfd
#

DAEMON=/etc/knot/nrfd_respawn

start() {
        printf "Starting nrfd: "
        $DAEMON &
        echo $! > /tmp/nrfd.pid
        echo "OK"
}

stop() {
        printf "Stopping nrfd: "
        kill `cat /tmp/nrfd.pid`
        echo "OK"
}

restart() {
        stop
        start
}


case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
