#!/bin/sh
#
# Run KNoT-fog
#

node /usr/local/bin/knot-fog-source/server.js &
echo $! > /tmp/knot-fog.pid

PIDFILE=/tmp/knot-fog.pid
PID=`cat $PIDFILE`

while [ -e /proc/$PID ]
do
	#Wait
	sleep 1
done
