#!/bin/sh
#
# Start KNoT-fog
#

start() {
        printf "Starting KNoT-fog: "
        if /etc/knot/start.sh knot-fog
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

stop() {
        printf "Stopping KNoT-fog: "
        if /etc/knot/stop.sh knot-fog
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

restart() {
        stop
        start
}


case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
