#!/bin/sh
#
# Run MongoDB
#

#Recover from unclean shutdown
if [ -s /data/db/mongod.lock ]
then
	mongod --repair
fi
mkdir -p /data/db
mongod --smallfiles --storageEngine mmapv1 &
echo $! > /tmp/mongod.pid

PIDFILE=/tmp/mongod.pid
PID=`cat $PIDFILE`

while [ -e /proc/$PID ]
do
	#Wait
	sleep 1
done
