#!/bin/sh
#
# Setup MongoDB instance
#

start() {
        printf "Starting MongoDB: "
        if /etc/knot/start.sh mongod
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

stop() {
        printf "Stopping MongoDB: "
        if /etc/knot/stop.sh mongod
        then
          echo "OK"
        else
          echo "FAIL"
        fi
}

restart() {
        stop
        start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
