#!/bin/sh
#
# Run KNoT WebUI
#

cd /usr/local/bin/knot-web-*/
NODE_ENV=production npm start &
echo $! > /tmp/knot-web.pid

PIDFILE=/tmp/knot-web.pid
PID=`cat $PIDFILE`

while [ -e /proc/$PID ]
do
        sleep 1
done
