#!/bin/sh
#
# at86rf230	Starts at86rf230.
#

start() {
	printf "Starting at86rf230: "
	modprobe at86rf230
	echo "OK"
}
stop() {
	printf "Stopping at86rf230: "
	rmmod at86rf230
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

