#!/bin/sh
#
# Start mainflux things service
#

NAME=things
DIR=/usr/local/mainflux
PID_FILE="/var/run/$NAME.pid"

set -a
source $DIR/things.conf

start() {
        printf "Starting Mainflux Things Service:"
        createdb -U postgres things
        start-stop-daemon -S -b -m -q -c mainflux:mainflux -p $PID_FILE --exec $DIR/bin/$NAME
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping Mainflux Things Service:"
        start-stop-daemon -K -q -p $PID_FILE
        rm $PID_FILE
        echo "OK"
}

restart() {
        stop
        start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

